### ISSUE TITLE
email test fail

### ISSUE THREAD

**Issue by runfan** [nettofarah/property-validator#23]
.mail@google.com shoud not pass isEmail
this is a bug
can you upgrade validator?

**Comment by nettofarah** [comment]
Hey, runfan.
Are you sure `.mail@google.com` is a valid email?

If so, can you test it against https://github.com/chriso/validator.js to make sure it works?
property-validator works on top of `validator.js`, so any failed validation would originate from the validation library.

Thanks

**Comment by runfan** [comment]
I found `.mail@google.com` pass on  https://github.com/chriso/validator.js
